<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../ConsumeMessageFromJMS.wsdl"/>
      <rootElement name="SSACompositeRequest" namespace="http://ssac.ee.sim.dsh.cms.hhs.gov"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../ConsumeMessageFromJMS.wsdl"/>
      <rootElement name="SSACompositeRequest" namespace="http://ssac.ee.sim.dsh.cms.hhs.gov"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.8(build 150622.2350.0222) AT [FRI JUL 15 10:22:41 EDT 2016]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns1="http://niem.gov/niem/niem-core/2.0"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/"
                xmlns:ns5="http://niem.gov/niem/appinfo/2.0"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns2="http://niem.gov/niem/structures/2.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns3="http://niem.gov/niem/usps_states/2.0"
                xmlns:imp1="http://ssac.ee.sim.dsh.cms.hhs.gov"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/Test/HavenSSAService/ConsumeMessageFromJMS"
                xmlns:ns4="http://codes.ssac.ee.sim.dsh.cms.hhs.gov"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns0="http://extn.ssac.ee.sim.dsh.cms.hhs.gov"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                xmlns:ns6="http://niem.gov/niem/proxy/xsd/2.0"
                exclude-result-prefixes="xsl xsi xsd plt ns1 pc ns5 ns2 ns3 imp1 tns ns4 wsdl ns0 jca ns6 oraext socket ora bpws xdk ids mhdr bpm xp20 hwf xref dvm med bpel ldap">
  <xsl:template match="/">
    <imp1:SSACompositeRequest>
      <xsl:if test="/imp1:SSACompositeRequest/@ns2:id">
        <xsl:attribute name="ns2:id">
          <xsl:value-of select="/imp1:SSACompositeRequest/@ns2:id"/>
        </xsl:attribute>
      </xsl:if>
      <xsl:if test="/imp1:SSACompositeRequest/@ns2:metadata">
        <xsl:attribute name="ns2:metadata">
          <xsl:value-of select="/imp1:SSACompositeRequest/@ns2:metadata"/>
        </xsl:attribute>
      </xsl:if>
      <xsl:if test="/imp1:SSACompositeRequest/@ns2:linkMetadata">
        <xsl:attribute name="ns2:linkMetadata">
          <xsl:value-of select="/imp1:SSACompositeRequest/@ns2:linkMetadata"/>
        </xsl:attribute>
      </xsl:if>
      <xsl:for-each select="/imp1:SSACompositeRequest/ns0:SSACompositeIndividualRequest">
        <ns0:SSACompositeIndividualRequest>
          <xsl:if test="@ns2:id">
            <xsl:attribute name="ns2:id">
              <xsl:value-of select="@ns2:id"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:if test="@ns2:metadata">
            <xsl:attribute name="ns2:metadata">
              <xsl:value-of select="@ns2:metadata"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:if test="@ns2:linkMetadata">
            <xsl:attribute name="ns2:linkMetadata">
              <xsl:value-of select="@ns2:linkMetadata"/>
            </xsl:attribute>
          </xsl:if>
          <ns0:Person>
            <xsl:if test="ns0:Person/@ns2:id">
              <xsl:attribute name="ns2:id">
                <xsl:value-of select="ns0:Person/@ns2:id"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:if test="ns0:Person/@ns2:metadata">
              <xsl:attribute name="ns2:metadata">
                <xsl:value-of select="ns0:Person/@ns2:metadata"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:if test="ns0:Person/@ns2:linkMetadata">
              <xsl:attribute name="ns2:linkMetadata">
                <xsl:value-of select="ns0:Person/@ns2:linkMetadata"/>
              </xsl:attribute>
            </xsl:if>
            <ns0:PersonSSNIdentification>
              <xsl:if test="ns0:Person/ns0:PersonSSNIdentification/@ns2:id">
                <xsl:attribute name="ns2:id">
                  <xsl:value-of select="ns0:Person/ns0:PersonSSNIdentification/@ns2:id"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:if test="ns0:Person/ns0:PersonSSNIdentification/@ns2:metadata">
                <xsl:attribute name="ns2:metadata">
                  <xsl:value-of select="ns0:Person/ns0:PersonSSNIdentification/@ns2:metadata"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:if test="ns0:Person/ns0:PersonSSNIdentification/@ns2:linkMetadata">
                <xsl:attribute name="ns2:linkMetadata">
                  <xsl:value-of select="ns0:Person/ns0:PersonSSNIdentification/@ns2:linkMetadata"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:Person/ns0:PersonSSNIdentification"/>
            </ns0:PersonSSNIdentification>
            <ns0:PersonName>
              <xsl:if test="ns0:Person/ns0:PersonName/@ns2:id">
                <xsl:attribute name="ns2:id">
                  <xsl:value-of select="ns0:Person/ns0:PersonName/@ns2:id"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:if test="ns0:Person/ns0:PersonName/@ns2:metadata">
                <xsl:attribute name="ns2:metadata">
                  <xsl:value-of select="ns0:Person/ns0:PersonName/@ns2:metadata"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:if test="ns0:Person/ns0:PersonName/@ns2:linkMetadata">
                <xsl:attribute name="ns2:linkMetadata">
                  <xsl:value-of select="ns0:Person/ns0:PersonName/@ns2:linkMetadata"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:if test="ns0:Person/ns0:PersonName/ns0:PersonGivenName">
                <ns0:PersonGivenName>
                  <xsl:if test="ns0:Person/ns0:PersonName/ns0:PersonGivenName/@ns2:id">
                    <xsl:attribute name="ns2:id">
                      <xsl:value-of select="ns0:Person/ns0:PersonName/ns0:PersonGivenName/@ns2:id"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns0:Person/ns0:PersonName/ns0:PersonGivenName/@ns2:metadata">
                    <xsl:attribute name="ns2:metadata">
                      <xsl:value-of select="ns0:Person/ns0:PersonName/ns0:PersonGivenName/@ns2:metadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns0:Person/ns0:PersonName/ns0:PersonGivenName/@ns2:linkMetadata">
                    <xsl:attribute name="ns2:linkMetadata">
                      <xsl:value-of select="ns0:Person/ns0:PersonName/ns0:PersonGivenName/@ns2:linkMetadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="ns0:Person/ns0:PersonName/ns0:PersonGivenName"/>
                </ns0:PersonGivenName>
              </xsl:if>
              <xsl:if test="ns0:Person/ns0:PersonName/ns0:PersonMiddleName">
                <ns0:PersonMiddleName>
                  <xsl:if test="ns0:Person/ns0:PersonName/ns0:PersonMiddleName/@ns2:id">
                    <xsl:attribute name="ns2:id">
                      <xsl:value-of select="ns0:Person/ns0:PersonName/ns0:PersonMiddleName/@ns2:id"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns0:Person/ns0:PersonName/ns0:PersonMiddleName/@ns2:metadata">
                    <xsl:attribute name="ns2:metadata">
                      <xsl:value-of select="ns0:Person/ns0:PersonName/ns0:PersonMiddleName/@ns2:metadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns0:Person/ns0:PersonName/ns0:PersonMiddleName/@ns2:linkMetadata">
                    <xsl:attribute name="ns2:linkMetadata">
                      <xsl:value-of select="ns0:Person/ns0:PersonName/ns0:PersonMiddleName/@ns2:linkMetadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="ns0:Person/ns0:PersonName/ns0:PersonMiddleName"/>
                </ns0:PersonMiddleName>
              </xsl:if>
              <ns0:PersonSurName>
                <xsl:if test="ns0:Person/ns0:PersonName/ns0:PersonSurName/@ns2:id">
                  <xsl:attribute name="ns2:id">
                    <xsl:value-of select="ns0:Person/ns0:PersonName/ns0:PersonSurName/@ns2:id"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:if test="ns0:Person/ns0:PersonName/ns0:PersonSurName/@ns2:metadata">
                  <xsl:attribute name="ns2:metadata">
                    <xsl:value-of select="ns0:Person/ns0:PersonName/ns0:PersonSurName/@ns2:metadata"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:if test="ns0:Person/ns0:PersonName/ns0:PersonSurName/@ns2:linkMetadata">
                  <xsl:attribute name="ns2:linkMetadata">
                    <xsl:value-of select="ns0:Person/ns0:PersonName/ns0:PersonSurName/@ns2:linkMetadata"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Person/ns0:PersonName/ns0:PersonSurName"/>
              </ns0:PersonSurName>
            </ns0:PersonName>
            <ns1:PersonBirthDate>
                     <xsl:if test="ns0:Person/ns1:PersonBirthDate/@ns2:id">
                        <xsl:attribute name="ns2:id">
                           <xsl:value-of select="ns0:Person/ns1:PersonBirthDate/@ns2:id"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:if test="ns0:Person/ns1:PersonBirthDate/@ns2:metadata">
                        <xsl:attribute name="ns2:metadata">
                           <xsl:value-of select="ns0:Person/ns1:PersonBirthDate/@ns2:metadata"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:if test="ns0:Person/ns1:PersonBirthDate/@ns2:linkMetadata">
                        <xsl:attribute name="ns2:linkMetadata">
                           <xsl:value-of select="ns0:Person/ns1:PersonBirthDate/@ns2:linkMetadata"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:if test="ns0:Person/ns1:PersonBirthDate/@xsi:nil">
                        <xsl:attribute name="xsi:nil">
                           <xsl:value-of select="ns0:Person/ns1:PersonBirthDate/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <ns1:Date>
                        <xsl:if test="ns0:Person/ns1:PersonBirthDate/ns1:Date/@ns2:id">
                           <xsl:attribute name="ns2:id">
                              <xsl:value-of select="ns0:Person/ns1:PersonBirthDate/ns1:Date/@ns2:id"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:if test="ns0:Person/ns1:PersonBirthDate/ns1:Date/@ns2:metadata">
                           <xsl:attribute name="ns2:metadata">
                              <xsl:value-of select="ns0:Person/ns1:PersonBirthDate/ns1:Date/@ns2:metadata"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:if test="ns0:Person/ns1:PersonBirthDate/ns1:Date/@ns2:linkMetadata">
                           <xsl:attribute name="ns2:linkMetadata">
                              <xsl:value-of select="ns0:Person/ns1:PersonBirthDate/ns1:Date/@ns2:linkMetadata"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:if test="ns0:Person/ns1:PersonBirthDate/ns1:Date/@xsi:nil">
                           <xsl:attribute name="xsi:nil">
                              <xsl:value-of select="ns0:Person/ns1:PersonBirthDate/ns1:Date/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:Person/ns1:PersonBirthDate/ns1:Date"/>
                     </ns1:Date>
                  </ns1:PersonBirthDate>
          </ns0:Person>
          <ns0:RequestCitizenshipVerificationIndicator>
            <xsl:if test="ns0:RequestCitizenshipVerificationIndicator/@ns2:id">
              <xsl:attribute name="ns2:id">
                <xsl:value-of select="ns0:RequestCitizenshipVerificationIndicator/@ns2:id"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:if test="ns0:RequestCitizenshipVerificationIndicator/@ns2:metadata">
              <xsl:attribute name="ns2:metadata">
                <xsl:value-of select="ns0:RequestCitizenshipVerificationIndicator/@ns2:metadata"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:if test="ns0:RequestCitizenshipVerificationIndicator/@ns2:linkMetadata">
              <xsl:attribute name="ns2:linkMetadata">
                <xsl:value-of select="ns0:RequestCitizenshipVerificationIndicator/@ns2:linkMetadata"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="ns0:RequestCitizenshipVerificationIndicator"/>
          </ns0:RequestCitizenshipVerificationIndicator>
          <ns0:RequestIncarcerationVerificationIndicator>
            <xsl:if test="ns0:RequestIncarcerationVerificationIndicator/@ns2:id">
              <xsl:attribute name="ns2:id">
                <xsl:value-of select="ns0:RequestIncarcerationVerificationIndicator/@ns2:id"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:if test="ns0:RequestIncarcerationVerificationIndicator/@ns2:metadata">
              <xsl:attribute name="ns2:metadata">
                <xsl:value-of select="ns0:RequestIncarcerationVerificationIndicator/@ns2:metadata"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:if test="ns0:RequestIncarcerationVerificationIndicator/@ns2:linkMetadata">
              <xsl:attribute name="ns2:linkMetadata">
                <xsl:value-of select="ns0:RequestIncarcerationVerificationIndicator/@ns2:linkMetadata"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="ns0:RequestIncarcerationVerificationIndicator"/>
          </ns0:RequestIncarcerationVerificationIndicator>
          <ns0:RequestTitleIIMonthlyIncomeVerificationIndicator>
            <xsl:if test="ns0:RequestTitleIIMonthlyIncomeVerificationIndicator/@ns2:id">
              <xsl:attribute name="ns2:id">
                <xsl:value-of select="ns0:RequestTitleIIMonthlyIncomeVerificationIndicator/@ns2:id"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:if test="ns0:RequestTitleIIMonthlyIncomeVerificationIndicator/@ns2:metadata">
              <xsl:attribute name="ns2:metadata">
                <xsl:value-of select="ns0:RequestTitleIIMonthlyIncomeVerificationIndicator/@ns2:metadata"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:if test="ns0:RequestTitleIIMonthlyIncomeVerificationIndicator/@ns2:linkMetadata">
              <xsl:attribute name="ns2:linkMetadata">
                <xsl:value-of select="ns0:RequestTitleIIMonthlyIncomeVerificationIndicator/@ns2:linkMetadata"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="ns0:RequestTitleIIMonthlyIncomeVerificationIndicator"/>
          </ns0:RequestTitleIIMonthlyIncomeVerificationIndicator>
          <ns0:RequestTitleIIAnnualIncomeVerificationIndicator>
            <xsl:if test="ns0:RequestTitleIIAnnualIncomeVerificationIndicator/@ns2:id">
              <xsl:attribute name="ns2:id">
                <xsl:value-of select="ns0:RequestTitleIIAnnualIncomeVerificationIndicator/@ns2:id"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:if test="ns0:RequestTitleIIAnnualIncomeVerificationIndicator/@ns2:metadata">
              <xsl:attribute name="ns2:metadata">
                <xsl:value-of select="ns0:RequestTitleIIAnnualIncomeVerificationIndicator/@ns2:metadata"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:if test="ns0:RequestTitleIIAnnualIncomeVerificationIndicator/@ns2:linkMetadata">
              <xsl:attribute name="ns2:linkMetadata">
                <xsl:value-of select="ns0:RequestTitleIIAnnualIncomeVerificationIndicator/@ns2:linkMetadata"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="ns0:RequestTitleIIAnnualIncomeVerificationIndicator"/>
          </ns0:RequestTitleIIAnnualIncomeVerificationIndicator>
          <ns0:RequestQuartersOfCoverageVerificationIndicator>
            <xsl:if test="ns0:RequestQuartersOfCoverageVerificationIndicator/@ns2:id">
              <xsl:attribute name="ns2:id">
                <xsl:value-of select="ns0:RequestQuartersOfCoverageVerificationIndicator/@ns2:id"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:if test="ns0:RequestQuartersOfCoverageVerificationIndicator/@ns2:metadata">
              <xsl:attribute name="ns2:metadata">
                <xsl:value-of select="ns0:RequestQuartersOfCoverageVerificationIndicator/@ns2:metadata"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:if test="ns0:RequestQuartersOfCoverageVerificationIndicator/@ns2:linkMetadata">
              <xsl:attribute name="ns2:linkMetadata">
                <xsl:value-of select="ns0:RequestQuartersOfCoverageVerificationIndicator/@ns2:linkMetadata"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="ns0:RequestQuartersOfCoverageVerificationIndicator"/>
          </ns0:RequestQuartersOfCoverageVerificationIndicator>
          <xsl:if test="ns0:RequestTitleIIMonthlyIncomeDate">
            <ns0:RequestTitleIIMonthlyIncomeDate>
              <xsl:value-of select="ns0:RequestTitleIIMonthlyIncomeDate"/>
            </ns0:RequestTitleIIMonthlyIncomeDate>
          </xsl:if>
          <xsl:if test="ns0:RequestTitleIIAnnualIncomeDate">
            <ns0:RequestTitleIIAnnualIncomeDate>
              <xsl:value-of select="ns0:RequestTitleIIAnnualIncomeDate"/>
            </ns0:RequestTitleIIAnnualIncomeDate>
          </xsl:if>
        </ns0:SSACompositeIndividualRequest>
      </xsl:for-each>
    </imp1:SSACompositeRequest>
  </xsl:template>
</xsl:stylesheet>
