<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../ConsumeMessageFromJMS.wsdl"/>
      <rootElement name="SSACompositeResponse" namespace="http://ssac.ee.sim.dsh.cms.hhs.gov"/>
    </source>
    <source type="WSDL">
      <schema location="../ConsumeMessageFromJMS.wsdl"/>
      <rootElement name="SSACompositeRequest" namespace="http://ssac.ee.sim.dsh.cms.hhs.gov"/>
      <param name="ConsumeMessage__InputVariable.body" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../ConsumeMessageFromJMS.wsdl"/>
      <rootElement name="SSACompositeResponse" namespace="http://ssac.ee.sim.dsh.cms.hhs.gov"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.8(build 150622.2350.0222) AT [FRI JUL 15 10:24:31 EDT 2016]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns1="http://niem.gov/niem/niem-core/2.0"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/"
                xmlns:ns5="http://niem.gov/niem/appinfo/2.0"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns2="http://niem.gov/niem/structures/2.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns3="http://niem.gov/niem/usps_states/2.0"
                xmlns:imp1="http://ssac.ee.sim.dsh.cms.hhs.gov"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/Test/HavenSSAService/ConsumeMessageFromJMS"
                xmlns:ns4="http://codes.ssac.ee.sim.dsh.cms.hhs.gov"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns0="http://extn.ssac.ee.sim.dsh.cms.hhs.gov"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                xmlns:ns6="http://niem.gov/niem/proxy/xsd/2.0"
                exclude-result-prefixes="xsl xsi xsd plt ns1 pc ns5 ns2 ns3 imp1 tns ns4 wsdl ns0 jca ns6 oraext socket ora bpws xdk ids mhdr bpm xp20 hwf xref dvm med bpel ldap">
  <xsl:param name="ConsumeMessage__InputVariable.body"/>
  <xsl:template match="/">
    <imp1:SSACompositeResponse>
      <xsl:if test="/imp1:SSACompositeResponse/@ns2:id">
        <xsl:attribute name="ns2:id">
          <xsl:value-of select="/imp1:SSACompositeResponse/@ns2:id"/>
        </xsl:attribute>
      </xsl:if>
      <xsl:if test="/imp1:SSACompositeResponse/@ns2:metadata">
        <xsl:attribute name="ns2:metadata">
          <xsl:value-of select="/imp1:SSACompositeResponse/@ns2:metadata"/>
        </xsl:attribute>
      </xsl:if>
      <xsl:if test="/imp1:SSACompositeResponse/@ns2:linkMetadata">
        <xsl:attribute name="ns2:linkMetadata">
          <xsl:value-of select="/imp1:SSACompositeResponse/@ns2:linkMetadata"/>
        </xsl:attribute>
      </xsl:if>
      <xsl:for-each select="/imp1:SSACompositeResponse/ns0:SSACompositeIndividualResponse">
        <ns0:SSACompositeIndividualResponse>
          <xsl:if test="@ns2:id">
            <xsl:attribute name="ns2:id">
              <xsl:value-of select="@ns2:id"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:if test="@ns2:metadata">
            <xsl:attribute name="ns2:metadata">
              <xsl:value-of select="@ns2:metadata"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:if test="@ns2:linkMetadata">
            <xsl:attribute name="ns2:linkMetadata">
              <xsl:value-of select="@ns2:linkMetadata"/>
            </xsl:attribute>
          </xsl:if>
          <ns0:ResponseMetadata>
            <xsl:if test="ns0:ResponseMetadata/@ns2:id">
              <xsl:attribute name="ns2:id">
                <xsl:value-of select="ns0:ResponseMetadata/@ns2:id"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:if test="ns0:ResponseMetadata/@ns2:metadata">
              <xsl:attribute name="ns2:metadata">
                <xsl:value-of select="ns0:ResponseMetadata/@ns2:metadata"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:if test="ns0:ResponseMetadata/@ns2:linkMetadata">
              <xsl:attribute name="ns2:linkMetadata">
                <xsl:value-of select="ns0:ResponseMetadata/@ns2:linkMetadata"/>
              </xsl:attribute>
            </xsl:if>
            <ns0:ResponseCode>
              <xsl:value-of select="ns0:ResponseMetadata/ns0:ResponseCode"/>
            </ns0:ResponseCode>
            <ns0:ResponseDescriptionText>
              <xsl:value-of select="ns0:ResponseMetadata/ns0:ResponseDescriptionText"/>
            </ns0:ResponseDescriptionText>
            <xsl:if test="ns0:ResponseMetadata/ns0:TDSResponseDescriptionText">
              <ns0:TDSResponseDescriptionText>
                <xsl:value-of select="ns0:ResponseMetadata/ns0:TDSResponseDescriptionText"/>
              </ns0:TDSResponseDescriptionText>
            </xsl:if>
          </ns0:ResponseMetadata>
          <ns0:PersonSSNIdentification>
            <xsl:if test="ns0:PersonSSNIdentification/@ns2:id">
              <xsl:attribute name="ns2:id">
                <xsl:value-of select="ns0:PersonSSNIdentification/@ns2:id"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:if test="ns0:PersonSSNIdentification/@ns2:metadata">
              <xsl:attribute name="ns2:metadata">
                <xsl:value-of select="ns0:PersonSSNIdentification/@ns2:metadata"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:if test="ns0:PersonSSNIdentification/@ns2:linkMetadata">
              <xsl:attribute name="ns2:linkMetadata">
                <xsl:value-of select="ns0:PersonSSNIdentification/@ns2:linkMetadata"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="ns0:PersonSSNIdentification"/>
          </ns0:PersonSSNIdentification>
          <xsl:if test="ns0:SSAResponse">
            <ns0:SSAResponse>
              <xsl:if test="ns0:SSAResponse/@ns2:id">
                <xsl:attribute name="ns2:id">
                  <xsl:value-of select="ns0:SSAResponse/@ns2:id"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:if test="ns0:SSAResponse/@ns2:metadata">
                <xsl:attribute name="ns2:metadata">
                  <xsl:value-of select="ns0:SSAResponse/@ns2:metadata"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:if test="ns0:SSAResponse/@ns2:linkMetadata">
                <xsl:attribute name="ns2:linkMetadata">
                  <xsl:value-of select="ns0:SSAResponse/@ns2:linkMetadata"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:if test="ns0:SSAResponse/ns0:SSNVerificationIndicator">
                <ns0:SSNVerificationIndicator>
                  <xsl:if test="ns0:SSAResponse/ns0:SSNVerificationIndicator/@ns2:id">
                    <xsl:attribute name="ns2:id">
                      <xsl:value-of select="ns0:SSAResponse/ns0:SSNVerificationIndicator/@ns2:id"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns0:SSAResponse/ns0:SSNVerificationIndicator/@ns2:metadata">
                    <xsl:attribute name="ns2:metadata">
                      <xsl:value-of select="ns0:SSAResponse/ns0:SSNVerificationIndicator/@ns2:metadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns0:SSAResponse/ns0:SSNVerificationIndicator/@ns2:linkMetadata">
                    <xsl:attribute name="ns2:linkMetadata">
                      <xsl:value-of select="ns0:SSAResponse/ns0:SSNVerificationIndicator/@ns2:linkMetadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="ns0:SSAResponse/ns0:SSNVerificationIndicator"/>
                </ns0:SSNVerificationIndicator>
              </xsl:if>
              <xsl:if test="ns0:SSAResponse/ns0:DeathConfirmationCode">
                <ns0:DeathConfirmationCode>
                  <xsl:value-of select="ns0:SSAResponse/ns0:DeathConfirmationCode"/>
                </ns0:DeathConfirmationCode>
              </xsl:if>
              <xsl:if test="ns0:SSAResponse/ns1:PersonUSCitizenIndicator">
                <ns1:PersonUSCitizenIndicator>
                  <xsl:if test="ns0:SSAResponse/ns1:PersonUSCitizenIndicator/@ns2:id">
                    <xsl:attribute name="ns2:id">
                      <xsl:value-of select="ns0:SSAResponse/ns1:PersonUSCitizenIndicator/@ns2:id"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns0:SSAResponse/ns1:PersonUSCitizenIndicator/@ns2:metadata">
                    <xsl:attribute name="ns2:metadata">
                      <xsl:value-of select="ns0:SSAResponse/ns1:PersonUSCitizenIndicator/@ns2:metadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns0:SSAResponse/ns1:PersonUSCitizenIndicator/@ns2:linkMetadata">
                    <xsl:attribute name="ns2:linkMetadata">
                      <xsl:value-of select="ns0:SSAResponse/ns1:PersonUSCitizenIndicator/@ns2:linkMetadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns0:SSAResponse/ns1:PersonUSCitizenIndicator/@xsi:nil">
                    <xsl:attribute name="xsi:nil">
                      <xsl:value-of select="ns0:SSAResponse/ns1:PersonUSCitizenIndicator/@xsi:nil"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="ns0:SSAResponse/ns1:PersonUSCitizenIndicator"/>
                </ns1:PersonUSCitizenIndicator>
              </xsl:if>
              <xsl:if test="ns0:SSAResponse/ns0:PersonIncarcerationInformationIndicator">
                <ns0:PersonIncarcerationInformationIndicator>
                  <xsl:if test="ns0:SSAResponse/ns0:PersonIncarcerationInformationIndicator/@ns2:id">
                    <xsl:attribute name="ns2:id">
                      <xsl:value-of select="ns0:SSAResponse/ns0:PersonIncarcerationInformationIndicator/@ns2:id"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns0:SSAResponse/ns0:PersonIncarcerationInformationIndicator/@ns2:metadata">
                    <xsl:attribute name="ns2:metadata">
                      <xsl:value-of select="ns0:SSAResponse/ns0:PersonIncarcerationInformationIndicator/@ns2:metadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns0:SSAResponse/ns0:PersonIncarcerationInformationIndicator/@ns2:linkMetadata">
                    <xsl:attribute name="ns2:linkMetadata">
                      <xsl:value-of select="ns0:SSAResponse/ns0:PersonIncarcerationInformationIndicator/@ns2:linkMetadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="ns0:SSAResponse/ns0:PersonIncarcerationInformationIndicator"/>
                </ns0:PersonIncarcerationInformationIndicator>
              </xsl:if>
              <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncomeInformationIndicator">
                <ns0:SSATitleIIMonthlyIncomeInformationIndicator>
                  <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncomeInformationIndicator/@ns2:id">
                    <xsl:attribute name="ns2:id">
                      <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncomeInformationIndicator/@ns2:id"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncomeInformationIndicator/@ns2:metadata">
                    <xsl:attribute name="ns2:metadata">
                      <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncomeInformationIndicator/@ns2:metadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncomeInformationIndicator/@ns2:linkMetadata">
                    <xsl:attribute name="ns2:linkMetadata">
                      <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncomeInformationIndicator/@ns2:linkMetadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncomeInformationIndicator"/>
                </ns0:SSATitleIIMonthlyIncomeInformationIndicator>
              </xsl:if>
              <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIAnnualIncomeInformationIndicator">
                <ns0:SSATitleIIAnnualIncomeInformationIndicator>
                  <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIAnnualIncomeInformationIndicator/@ns2:id">
                    <xsl:attribute name="ns2:id">
                      <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIAnnualIncomeInformationIndicator/@ns2:id"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIAnnualIncomeInformationIndicator/@ns2:metadata">
                    <xsl:attribute name="ns2:metadata">
                      <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIAnnualIncomeInformationIndicator/@ns2:metadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIAnnualIncomeInformationIndicator/@ns2:linkMetadata">
                    <xsl:attribute name="ns2:linkMetadata">
                      <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIAnnualIncomeInformationIndicator/@ns2:linkMetadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIAnnualIncomeInformationIndicator"/>
                </ns0:SSATitleIIAnnualIncomeInformationIndicator>
              </xsl:if>
              <xsl:if test="ns0:SSAResponse/ns0:SSAQuartersOfCoverageInformationIndicator">
                <ns0:SSAQuartersOfCoverageInformationIndicator>
                  <xsl:if test="ns0:SSAResponse/ns0:SSAQuartersOfCoverageInformationIndicator/@ns2:id">
                    <xsl:attribute name="ns2:id">
                      <xsl:value-of select="ns0:SSAResponse/ns0:SSAQuartersOfCoverageInformationIndicator/@ns2:id"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns0:SSAResponse/ns0:SSAQuartersOfCoverageInformationIndicator/@ns2:metadata">
                    <xsl:attribute name="ns2:metadata">
                      <xsl:value-of select="ns0:SSAResponse/ns0:SSAQuartersOfCoverageInformationIndicator/@ns2:metadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns0:SSAResponse/ns0:SSAQuartersOfCoverageInformationIndicator/@ns2:linkMetadata">
                    <xsl:attribute name="ns2:linkMetadata">
                      <xsl:value-of select="ns0:SSAResponse/ns0:SSAQuartersOfCoverageInformationIndicator/@ns2:linkMetadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="ns0:SSAResponse/ns0:SSAQuartersOfCoverageInformationIndicator"/>
                </ns0:SSAQuartersOfCoverageInformationIndicator>
              </xsl:if>
              <xsl:if test="ns0:SSAResponse/ns0:SSAIncarcerationInformation">
                <ns0:SSAIncarcerationInformation>
                  <xsl:if test="ns0:SSAResponse/ns0:SSAIncarcerationInformation/@ns2:id">
                    <xsl:attribute name="ns2:id">
                      <xsl:value-of select="ns0:SSAResponse/ns0:SSAIncarcerationInformation/@ns2:id"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns0:SSAResponse/ns0:SSAIncarcerationInformation/@ns2:metadata">
                    <xsl:attribute name="ns2:metadata">
                      <xsl:value-of select="ns0:SSAResponse/ns0:SSAIncarcerationInformation/@ns2:metadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns0:SSAResponse/ns0:SSAIncarcerationInformation/@ns2:linkMetadata">
                    <xsl:attribute name="ns2:linkMetadata">
                      <xsl:value-of select="ns0:SSAResponse/ns0:SSAIncarcerationInformation/@ns2:linkMetadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <ns0:PrisonerIdentification>
                    <xsl:value-of select="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:PrisonerIdentification"/>
                  </ns0:PrisonerIdentification>
                  <ns0:PrisonerConfinementDate>
                    <xsl:value-of select="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:PrisonerConfinementDate"/>
                  </ns0:PrisonerConfinementDate>
                  <ns0:ReportingPersonText>
                    <xsl:value-of select="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:ReportingPersonText"/>
                  </ns0:ReportingPersonText>
                  <ns0:SupervisionFacility>
                    <xsl:if test="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:SupervisionFacility/@ns2:id">
                      <xsl:attribute name="ns2:id">
                        <xsl:value-of select="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:SupervisionFacility/@ns2:id"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:SupervisionFacility/@ns2:metadata">
                      <xsl:attribute name="ns2:metadata">
                        <xsl:value-of select="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:SupervisionFacility/@ns2:metadata"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:SupervisionFacility/@ns2:linkMetadata">
                      <xsl:attribute name="ns2:linkMetadata">
                        <xsl:value-of select="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:SupervisionFacility/@ns2:linkMetadata"/>
                      </xsl:attribute>
                    </xsl:if>
                    <ns0:FacilityName>
                      <xsl:value-of select="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:SupervisionFacility/ns0:FacilityName"/>
                    </ns0:FacilityName>
                    <ns0:FacilityLocation>
                      <xsl:if test="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:SupervisionFacility/ns0:FacilityLocation/@ns2:id">
                        <xsl:attribute name="ns2:id">
                          <xsl:value-of select="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:SupervisionFacility/ns0:FacilityLocation/@ns2:id"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:SupervisionFacility/ns0:FacilityLocation/@ns2:metadata">
                        <xsl:attribute name="ns2:metadata">
                          <xsl:value-of select="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:SupervisionFacility/ns0:FacilityLocation/@ns2:metadata"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:SupervisionFacility/ns0:FacilityLocation/@ns2:linkMetadata">
                        <xsl:attribute name="ns2:linkMetadata">
                          <xsl:value-of select="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:SupervisionFacility/ns0:FacilityLocation/@ns2:linkMetadata"/>
                        </xsl:attribute>
                      </xsl:if>
                      <ns0:LocationStreet>
                        <xsl:value-of select="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:SupervisionFacility/ns0:FacilityLocation/ns0:LocationStreet"/>
                      </ns0:LocationStreet>
                      <ns0:LocationCityName>
                        <xsl:value-of select="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:SupervisionFacility/ns0:FacilityLocation/ns0:LocationCityName"/>
                      </ns0:LocationCityName>
                      <ns1:LocationStateUSPostalServiceCode>
                        <xsl:if test="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:SupervisionFacility/ns0:FacilityLocation/ns1:LocationStateUSPostalServiceCode/@ns2:id">
                          <xsl:attribute name="ns2:id">
                            <xsl:value-of select="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:SupervisionFacility/ns0:FacilityLocation/ns1:LocationStateUSPostalServiceCode/@ns2:id"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:if test="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:SupervisionFacility/ns0:FacilityLocation/ns1:LocationStateUSPostalServiceCode/@ns2:metadata">
                          <xsl:attribute name="ns2:metadata">
                            <xsl:value-of select="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:SupervisionFacility/ns0:FacilityLocation/ns1:LocationStateUSPostalServiceCode/@ns2:metadata"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:if test="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:SupervisionFacility/ns0:FacilityLocation/ns1:LocationStateUSPostalServiceCode/@ns2:linkMetadata">
                          <xsl:attribute name="ns2:linkMetadata">
                            <xsl:value-of select="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:SupervisionFacility/ns0:FacilityLocation/ns1:LocationStateUSPostalServiceCode/@ns2:linkMetadata"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:if test="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:SupervisionFacility/ns0:FacilityLocation/ns1:LocationStateUSPostalServiceCode/@xsi:nil">
                          <xsl:attribute name="xsi:nil">
                            <xsl:value-of select="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:SupervisionFacility/ns0:FacilityLocation/ns1:LocationStateUSPostalServiceCode/@xsi:nil"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:SupervisionFacility/ns0:FacilityLocation/ns1:LocationStateUSPostalServiceCode"/>
                      </ns1:LocationStateUSPostalServiceCode>
                      <ns0:LocationPostalCode>
                        <xsl:value-of select="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:SupervisionFacility/ns0:FacilityLocation/ns0:LocationPostalCode"/>
                      </ns0:LocationPostalCode>
                    </ns0:FacilityLocation>
                    <ns0:FacilityContactInformation>
                      <xsl:if test="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:SupervisionFacility/ns0:FacilityContactInformation/@ns2:id">
                        <xsl:attribute name="ns2:id">
                          <xsl:value-of select="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:SupervisionFacility/ns0:FacilityContactInformation/@ns2:id"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:SupervisionFacility/ns0:FacilityContactInformation/@ns2:metadata">
                        <xsl:attribute name="ns2:metadata">
                          <xsl:value-of select="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:SupervisionFacility/ns0:FacilityContactInformation/@ns2:metadata"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:SupervisionFacility/ns0:FacilityContactInformation/@ns2:linkMetadata">
                        <xsl:attribute name="ns2:linkMetadata">
                          <xsl:value-of select="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:SupervisionFacility/ns0:FacilityContactInformation/@ns2:linkMetadata"/>
                        </xsl:attribute>
                      </xsl:if>
                      <ns0:PersonFullName>
                        <xsl:value-of select="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:SupervisionFacility/ns0:FacilityContactInformation/ns0:PersonFullName"/>
                      </ns0:PersonFullName>
                      <ns0:ContactTelephoneNumber>
                        <xsl:value-of select="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:SupervisionFacility/ns0:FacilityContactInformation/ns0:ContactTelephoneNumber"/>
                      </ns0:ContactTelephoneNumber>
                      <ns0:ContactFaxNumber>
                        <xsl:value-of select="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:SupervisionFacility/ns0:FacilityContactInformation/ns0:ContactFaxNumber"/>
                      </ns0:ContactFaxNumber>
                    </ns0:FacilityContactInformation>
                    <ns0:FacilityCategoryCode>
                      <xsl:value-of select="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:SupervisionFacility/ns0:FacilityCategoryCode"/>
                    </ns0:FacilityCategoryCode>
                  </ns0:SupervisionFacility>
                  <ns0:InmateStatusIndicator>
                    <xsl:if test="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:InmateStatusIndicator/@ns2:id">
                      <xsl:attribute name="ns2:id">
                        <xsl:value-of select="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:InmateStatusIndicator/@ns2:id"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:InmateStatusIndicator/@ns2:metadata">
                      <xsl:attribute name="ns2:metadata">
                        <xsl:value-of select="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:InmateStatusIndicator/@ns2:metadata"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:InmateStatusIndicator/@ns2:linkMetadata">
                      <xsl:attribute name="ns2:linkMetadata">
                        <xsl:value-of select="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:InmateStatusIndicator/@ns2:linkMetadata"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:SSAResponse/ns0:SSAIncarcerationInformation/ns0:InmateStatusIndicator"/>
                  </ns0:InmateStatusIndicator>
                </ns0:SSAIncarcerationInformation>
              </xsl:if>
              <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome">
                <ns0:SSATitleIIMonthlyIncome>
                  <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/@ns2:id">
                    <xsl:attribute name="ns2:id">
                      <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/@ns2:id"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/@ns2:metadata">
                    <xsl:attribute name="ns2:metadata">
                      <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/@ns2:metadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/@ns2:linkMetadata">
                    <xsl:attribute name="ns2:linkMetadata">
                      <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/@ns2:linkMetadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <ns0:PersonDisabledIndicator>
                    <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:PersonDisabledIndicator/@ns2:id">
                      <xsl:attribute name="ns2:id">
                        <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:PersonDisabledIndicator/@ns2:id"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:PersonDisabledIndicator/@ns2:metadata">
                      <xsl:attribute name="ns2:metadata">
                        <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:PersonDisabledIndicator/@ns2:metadata"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:PersonDisabledIndicator/@ns2:linkMetadata">
                      <xsl:attribute name="ns2:linkMetadata">
                        <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:PersonDisabledIndicator/@ns2:linkMetadata"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:PersonDisabledIndicator"/>
                  </ns0:PersonDisabledIndicator>
                  <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:OngoingMonthlyBenefitCreditedAmount">
                    <ns0:OngoingMonthlyBenefitCreditedAmount>
                      <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:OngoingMonthlyBenefitCreditedAmount"/>
                    </ns0:OngoingMonthlyBenefitCreditedAmount>
                  </xsl:if>
                  <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:OngoingMonthlyOverpaymentDeductionAmount">
                    <ns0:OngoingMonthlyOverpaymentDeductionAmount>
                      <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:OngoingMonthlyOverpaymentDeductionAmount"/>
                    </ns0:OngoingMonthlyOverpaymentDeductionAmount>
                  </xsl:if>
                  <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:OngoingPaymentInSuspenseIndicator">
                    <ns0:OngoingPaymentInSuspenseIndicator>
                      <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:OngoingPaymentInSuspenseIndicator/@ns2:id">
                        <xsl:attribute name="ns2:id">
                          <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:OngoingPaymentInSuspenseIndicator/@ns2:id"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:OngoingPaymentInSuspenseIndicator/@ns2:metadata">
                        <xsl:attribute name="ns2:metadata">
                          <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:OngoingPaymentInSuspenseIndicator/@ns2:metadata"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:OngoingPaymentInSuspenseIndicator/@ns2:linkMetadata">
                        <xsl:attribute name="ns2:linkMetadata">
                          <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:OngoingPaymentInSuspenseIndicator/@ns2:linkMetadata"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:OngoingPaymentInSuspenseIndicator"/>
                    </ns0:OngoingPaymentInSuspenseIndicator>
                  </xsl:if>
                  <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthInformation">
                    <ns0:RequestedMonthInformation>
                      <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthInformation/@ns2:id">
                        <xsl:attribute name="ns2:id">
                          <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthInformation/@ns2:id"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthInformation/@ns2:metadata">
                        <xsl:attribute name="ns2:metadata">
                          <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthInformation/@ns2:metadata"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthInformation/@ns2:linkMetadata">
                        <xsl:attribute name="ns2:linkMetadata">
                          <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthInformation/@ns2:linkMetadata"/>
                        </xsl:attribute>
                      </xsl:if>
                      <ns0:IncomeMonthYear>
                        <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthInformation/ns0:IncomeMonthYear"/>
                      </ns0:IncomeMonthYear>
                      <ns0:BenefitCreditedAmount>
                        <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthInformation/ns0:BenefitCreditedAmount"/>
                      </ns0:BenefitCreditedAmount>
                      <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthInformation/ns0:OverpaymentDeductionAmount">
                        <ns0:OverpaymentDeductionAmount>
                          <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthInformation/ns0:OverpaymentDeductionAmount"/>
                        </ns0:OverpaymentDeductionAmount>
                      </xsl:if>
                      <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthInformation/ns0:PriorMonthAccrualAmount">
                        <ns0:PriorMonthAccrualAmount>
                          <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthInformation/ns0:PriorMonthAccrualAmount"/>
                        </ns0:PriorMonthAccrualAmount>
                      </xsl:if>
                      <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthInformation/ns0:ReturnedCheckAmount">
                        <ns0:ReturnedCheckAmount>
                          <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthInformation/ns0:ReturnedCheckAmount"/>
                        </ns0:ReturnedCheckAmount>
                      </xsl:if>
                      <ns0:PaymentInSuspenseIndicator>
                        <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthInformation/ns0:PaymentInSuspenseIndicator/@ns2:id">
                          <xsl:attribute name="ns2:id">
                            <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthInformation/ns0:PaymentInSuspenseIndicator/@ns2:id"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthInformation/ns0:PaymentInSuspenseIndicator/@ns2:metadata">
                          <xsl:attribute name="ns2:metadata">
                            <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthInformation/ns0:PaymentInSuspenseIndicator/@ns2:metadata"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthInformation/ns0:PaymentInSuspenseIndicator/@ns2:linkMetadata">
                          <xsl:attribute name="ns2:linkMetadata">
                            <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthInformation/ns0:PaymentInSuspenseIndicator/@ns2:linkMetadata"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthInformation/ns0:PaymentInSuspenseIndicator"/>
                      </ns0:PaymentInSuspenseIndicator>
                      <ns0:NetMonthlyBenefitCreditedAmount>
                        <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthInformation/ns0:NetMonthlyBenefitCreditedAmount"/>
                      </ns0:NetMonthlyBenefitCreditedAmount>
                      <ns0:MonthlyIncomeAmount>
                        <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthInformation/ns0:MonthlyIncomeAmount"/>
                      </ns0:MonthlyIncomeAmount>
                    </ns0:RequestedMonthInformation>
                  </xsl:if>
                  <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusOneInformation">
                    <ns0:RequestedMonthMinusOneInformation>
                      <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusOneInformation/@ns2:id">
                        <xsl:attribute name="ns2:id">
                          <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusOneInformation/@ns2:id"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusOneInformation/@ns2:metadata">
                        <xsl:attribute name="ns2:metadata">
                          <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusOneInformation/@ns2:metadata"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusOneInformation/@ns2:linkMetadata">
                        <xsl:attribute name="ns2:linkMetadata">
                          <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusOneInformation/@ns2:linkMetadata"/>
                        </xsl:attribute>
                      </xsl:if>
                      <ns0:IncomeMonthYear>
                        <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusOneInformation/ns0:IncomeMonthYear"/>
                      </ns0:IncomeMonthYear>
                      <ns0:BenefitCreditedAmount>
                        <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusOneInformation/ns0:BenefitCreditedAmount"/>
                      </ns0:BenefitCreditedAmount>
                      <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusOneInformation/ns0:OverpaymentDeductionAmount">
                        <ns0:OverpaymentDeductionAmount>
                          <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusOneInformation/ns0:OverpaymentDeductionAmount"/>
                        </ns0:OverpaymentDeductionAmount>
                      </xsl:if>
                      <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusOneInformation/ns0:PriorMonthAccrualAmount">
                        <ns0:PriorMonthAccrualAmount>
                          <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusOneInformation/ns0:PriorMonthAccrualAmount"/>
                        </ns0:PriorMonthAccrualAmount>
                      </xsl:if>
                      <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusOneInformation/ns0:ReturnedCheckAmount">
                        <ns0:ReturnedCheckAmount>
                          <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusOneInformation/ns0:ReturnedCheckAmount"/>
                        </ns0:ReturnedCheckAmount>
                      </xsl:if>
                      <ns0:PaymentInSuspenseIndicator>
                        <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusOneInformation/ns0:PaymentInSuspenseIndicator/@ns2:id">
                          <xsl:attribute name="ns2:id">
                            <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusOneInformation/ns0:PaymentInSuspenseIndicator/@ns2:id"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusOneInformation/ns0:PaymentInSuspenseIndicator/@ns2:metadata">
                          <xsl:attribute name="ns2:metadata">
                            <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusOneInformation/ns0:PaymentInSuspenseIndicator/@ns2:metadata"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusOneInformation/ns0:PaymentInSuspenseIndicator/@ns2:linkMetadata">
                          <xsl:attribute name="ns2:linkMetadata">
                            <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusOneInformation/ns0:PaymentInSuspenseIndicator/@ns2:linkMetadata"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusOneInformation/ns0:PaymentInSuspenseIndicator"/>
                      </ns0:PaymentInSuspenseIndicator>
                      <ns0:NetMonthlyBenefitCreditedAmount>
                        <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusOneInformation/ns0:NetMonthlyBenefitCreditedAmount"/>
                      </ns0:NetMonthlyBenefitCreditedAmount>
                      <ns0:MonthlyIncomeAmount>
                        <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusOneInformation/ns0:MonthlyIncomeAmount"/>
                      </ns0:MonthlyIncomeAmount>
                    </ns0:RequestedMonthMinusOneInformation>
                  </xsl:if>
                  <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusTwoInformation">
                    <ns0:RequestedMonthMinusTwoInformation>
                      <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusTwoInformation/@ns2:id">
                        <xsl:attribute name="ns2:id">
                          <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusTwoInformation/@ns2:id"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusTwoInformation/@ns2:metadata">
                        <xsl:attribute name="ns2:metadata">
                          <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusTwoInformation/@ns2:metadata"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusTwoInformation/@ns2:linkMetadata">
                        <xsl:attribute name="ns2:linkMetadata">
                          <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusTwoInformation/@ns2:linkMetadata"/>
                        </xsl:attribute>
                      </xsl:if>
                      <ns0:IncomeMonthYear>
                        <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusTwoInformation/ns0:IncomeMonthYear"/>
                      </ns0:IncomeMonthYear>
                      <ns0:BenefitCreditedAmount>
                        <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusTwoInformation/ns0:BenefitCreditedAmount"/>
                      </ns0:BenefitCreditedAmount>
                      <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusTwoInformation/ns0:OverpaymentDeductionAmount">
                        <ns0:OverpaymentDeductionAmount>
                          <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusTwoInformation/ns0:OverpaymentDeductionAmount"/>
                        </ns0:OverpaymentDeductionAmount>
                      </xsl:if>
                      <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusTwoInformation/ns0:PriorMonthAccrualAmount">
                        <ns0:PriorMonthAccrualAmount>
                          <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusTwoInformation/ns0:PriorMonthAccrualAmount"/>
                        </ns0:PriorMonthAccrualAmount>
                      </xsl:if>
                      <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusTwoInformation/ns0:ReturnedCheckAmount">
                        <ns0:ReturnedCheckAmount>
                          <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusTwoInformation/ns0:ReturnedCheckAmount"/>
                        </ns0:ReturnedCheckAmount>
                      </xsl:if>
                      <ns0:PaymentInSuspenseIndicator>
                        <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusTwoInformation/ns0:PaymentInSuspenseIndicator/@ns2:id">
                          <xsl:attribute name="ns2:id">
                            <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusTwoInformation/ns0:PaymentInSuspenseIndicator/@ns2:id"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusTwoInformation/ns0:PaymentInSuspenseIndicator/@ns2:metadata">
                          <xsl:attribute name="ns2:metadata">
                            <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusTwoInformation/ns0:PaymentInSuspenseIndicator/@ns2:metadata"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusTwoInformation/ns0:PaymentInSuspenseIndicator/@ns2:linkMetadata">
                          <xsl:attribute name="ns2:linkMetadata">
                            <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusTwoInformation/ns0:PaymentInSuspenseIndicator/@ns2:linkMetadata"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusTwoInformation/ns0:PaymentInSuspenseIndicator"/>
                      </ns0:PaymentInSuspenseIndicator>
                      <ns0:NetMonthlyBenefitCreditedAmount>
                        <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusTwoInformation/ns0:NetMonthlyBenefitCreditedAmount"/>
                      </ns0:NetMonthlyBenefitCreditedAmount>
                      <ns0:MonthlyIncomeAmount>
                        <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusTwoInformation/ns0:MonthlyIncomeAmount"/>
                      </ns0:MonthlyIncomeAmount>
                    </ns0:RequestedMonthMinusTwoInformation>
                  </xsl:if>
                  <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusThreeInformation">
                    <ns0:RequestedMonthMinusThreeInformation>
                      <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusThreeInformation/@ns2:id">
                        <xsl:attribute name="ns2:id">
                          <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusThreeInformation/@ns2:id"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusThreeInformation/@ns2:metadata">
                        <xsl:attribute name="ns2:metadata">
                          <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusThreeInformation/@ns2:metadata"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusThreeInformation/@ns2:linkMetadata">
                        <xsl:attribute name="ns2:linkMetadata">
                          <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusThreeInformation/@ns2:linkMetadata"/>
                        </xsl:attribute>
                      </xsl:if>
                      <ns0:IncomeMonthYear>
                        <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusThreeInformation/ns0:IncomeMonthYear"/>
                      </ns0:IncomeMonthYear>
                      <ns0:BenefitCreditedAmount>
                        <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusThreeInformation/ns0:BenefitCreditedAmount"/>
                      </ns0:BenefitCreditedAmount>
                      <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusThreeInformation/ns0:OverpaymentDeductionAmount">
                        <ns0:OverpaymentDeductionAmount>
                          <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusThreeInformation/ns0:OverpaymentDeductionAmount"/>
                        </ns0:OverpaymentDeductionAmount>
                      </xsl:if>
                      <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusThreeInformation/ns0:PriorMonthAccrualAmount">
                        <ns0:PriorMonthAccrualAmount>
                          <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusThreeInformation/ns0:PriorMonthAccrualAmount"/>
                        </ns0:PriorMonthAccrualAmount>
                      </xsl:if>
                      <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusThreeInformation/ns0:ReturnedCheckAmount">
                        <ns0:ReturnedCheckAmount>
                          <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusThreeInformation/ns0:ReturnedCheckAmount"/>
                        </ns0:ReturnedCheckAmount>
                      </xsl:if>
                      <ns0:PaymentInSuspenseIndicator>
                        <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusThreeInformation/ns0:PaymentInSuspenseIndicator/@ns2:id">
                          <xsl:attribute name="ns2:id">
                            <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusThreeInformation/ns0:PaymentInSuspenseIndicator/@ns2:id"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusThreeInformation/ns0:PaymentInSuspenseIndicator/@ns2:metadata">
                          <xsl:attribute name="ns2:metadata">
                            <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusThreeInformation/ns0:PaymentInSuspenseIndicator/@ns2:metadata"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusThreeInformation/ns0:PaymentInSuspenseIndicator/@ns2:linkMetadata">
                          <xsl:attribute name="ns2:linkMetadata">
                            <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusThreeInformation/ns0:PaymentInSuspenseIndicator/@ns2:linkMetadata"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusThreeInformation/ns0:PaymentInSuspenseIndicator"/>
                      </ns0:PaymentInSuspenseIndicator>
                      <ns0:NetMonthlyBenefitCreditedAmount>
                        <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusThreeInformation/ns0:NetMonthlyBenefitCreditedAmount"/>
                      </ns0:NetMonthlyBenefitCreditedAmount>
                      <ns0:MonthlyIncomeAmount>
                        <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIMonthlyIncome/ns0:RequestedMonthMinusThreeInformation/ns0:MonthlyIncomeAmount"/>
                      </ns0:MonthlyIncomeAmount>
                    </ns0:RequestedMonthMinusThreeInformation>
                  </xsl:if>
                </ns0:SSATitleIIMonthlyIncome>
              </xsl:if>
              <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIYearlyIncome">
                <ns0:SSATitleIIYearlyIncome>
                  <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIYearlyIncome/@ns2:id">
                    <xsl:attribute name="ns2:id">
                      <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIYearlyIncome/@ns2:id"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIYearlyIncome/@ns2:metadata">
                    <xsl:attribute name="ns2:metadata">
                      <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIYearlyIncome/@ns2:metadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIYearlyIncome/@ns2:linkMetadata">
                    <xsl:attribute name="ns2:linkMetadata">
                      <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIYearlyIncome/@ns2:linkMetadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIYearlyIncome/ns0:TitleIIRequestedYearInformation">
                    <ns0:TitleIIRequestedYearInformation>
                      <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIYearlyIncome/ns0:TitleIIRequestedYearInformation/@ns2:id">
                        <xsl:attribute name="ns2:id">
                          <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIYearlyIncome/ns0:TitleIIRequestedYearInformation/@ns2:id"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIYearlyIncome/ns0:TitleIIRequestedYearInformation/@ns2:metadata">
                        <xsl:attribute name="ns2:metadata">
                          <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIYearlyIncome/ns0:TitleIIRequestedYearInformation/@ns2:metadata"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="ns0:SSAResponse/ns0:SSATitleIIYearlyIncome/ns0:TitleIIRequestedYearInformation/@ns2:linkMetadata">
                        <xsl:attribute name="ns2:linkMetadata">
                          <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIYearlyIncome/ns0:TitleIIRequestedYearInformation/@ns2:linkMetadata"/>
                        </xsl:attribute>
                      </xsl:if>
                      <ns0:IncomeDate>
                        <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIYearlyIncome/ns0:TitleIIRequestedYearInformation/ns0:IncomeDate"/>
                      </ns0:IncomeDate>
                      <ns0:YearlyIncomeAmount>
                        <xsl:value-of select="ns0:SSAResponse/ns0:SSATitleIIYearlyIncome/ns0:TitleIIRequestedYearInformation/ns0:YearlyIncomeAmount"/>
                      </ns0:YearlyIncomeAmount>
                    </ns0:TitleIIRequestedYearInformation>
                  </xsl:if>
                </ns0:SSATitleIIYearlyIncome>
              </xsl:if>
              <xsl:if test="ns0:SSAResponse/ns0:SSAQuartersOfCoverage">
                <ns0:SSAQuartersOfCoverage>
                  <xsl:if test="ns0:SSAResponse/ns0:SSAQuartersOfCoverage/@ns2:id">
                    <xsl:attribute name="ns2:id">
                      <xsl:value-of select="ns0:SSAResponse/ns0:SSAQuartersOfCoverage/@ns2:id"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns0:SSAResponse/ns0:SSAQuartersOfCoverage/@ns2:metadata">
                    <xsl:attribute name="ns2:metadata">
                      <xsl:value-of select="ns0:SSAResponse/ns0:SSAQuartersOfCoverage/@ns2:metadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="ns0:SSAResponse/ns0:SSAQuartersOfCoverage/@ns2:linkMetadata">
                    <xsl:attribute name="ns2:linkMetadata">
                      <xsl:value-of select="ns0:SSAResponse/ns0:SSAQuartersOfCoverage/@ns2:linkMetadata"/>
                    </xsl:attribute>
                  </xsl:if>
                  <ns0:LifeTimeQuarterQuantity>
                    <xsl:value-of select="ns0:SSAResponse/ns0:SSAQuartersOfCoverage/ns0:LifeTimeQuarterQuantity"/>
                  </ns0:LifeTimeQuarterQuantity>
                  <xsl:for-each select="ns0:SSAResponse/ns0:SSAQuartersOfCoverage/ns0:QualifyingYearAndQuarter">
                    <ns0:QualifyingYearAndQuarter>
                      <xsl:if test="@ns2:id">
                        <xsl:attribute name="ns2:id">
                          <xsl:value-of select="@ns2:id"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="@ns2:metadata">
                        <xsl:attribute name="ns2:metadata">
                          <xsl:value-of select="@ns2:metadata"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="@ns2:linkMetadata">
                        <xsl:attribute name="ns2:linkMetadata">
                          <xsl:value-of select="@ns2:linkMetadata"/>
                        </xsl:attribute>
                      </xsl:if>
                      <ns0:QualifyingYear>
                        <xsl:if test="ns0:QualifyingYear/@ns2:id">
                          <xsl:attribute name="ns2:id">
                            <xsl:value-of select="ns0:QualifyingYear/@ns2:id"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:if test="ns0:QualifyingYear/@ns2:metadata">
                          <xsl:attribute name="ns2:metadata">
                            <xsl:value-of select="ns0:QualifyingYear/@ns2:metadata"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:if test="ns0:QualifyingYear/@ns2:linkMetadata">
                          <xsl:attribute name="ns2:linkMetadata">
                            <xsl:value-of select="ns0:QualifyingYear/@ns2:linkMetadata"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="ns0:QualifyingYear"/>
                      </ns0:QualifyingYear>
                      <ns0:QualifyingQuarter>
                        <xsl:value-of select="ns0:QualifyingQuarter"/>
                      </ns0:QualifyingQuarter>
                    </ns0:QualifyingYearAndQuarter>
                  </xsl:for-each>
                </ns0:SSAQuartersOfCoverage>
              </xsl:if>
            </ns0:SSAResponse>
          </xsl:if>
        </ns0:SSACompositeIndividualResponse>
      </xsl:for-each>
      <ns0:ResponseMetadata>
        <xsl:if test="/imp1:SSACompositeResponse/ns0:ResponseMetadata/@ns2:id">
          <xsl:attribute name="ns2:id">
            <xsl:value-of select="/imp1:SSACompositeResponse/ns0:ResponseMetadata/@ns2:id"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:if test="/imp1:SSACompositeResponse/ns0:ResponseMetadata/@ns2:metadata">
          <xsl:attribute name="ns2:metadata">
            <xsl:value-of select="/imp1:SSACompositeResponse/ns0:ResponseMetadata/@ns2:metadata"/>
          </xsl:attribute>
        </xsl:if>
        <xsl:if test="/imp1:SSACompositeResponse/ns0:ResponseMetadata/@ns2:linkMetadata">
          <xsl:attribute name="ns2:linkMetadata">
            <xsl:value-of select="/imp1:SSACompositeResponse/ns0:ResponseMetadata/@ns2:linkMetadata"/>
          </xsl:attribute>
        </xsl:if>
        <ns0:ResponseCode>
          <xsl:value-of select="/imp1:SSACompositeResponse/ns0:ResponseMetadata/ns0:ResponseCode"/>
        </ns0:ResponseCode>
        <ns0:ResponseDescriptionText>
          <xsl:value-of select="/imp1:SSACompositeResponse/ns0:ResponseMetadata/ns0:ResponseDescriptionText"/>
        </ns0:ResponseDescriptionText>
        <xsl:if test="/imp1:SSACompositeResponse/ns0:ResponseMetadata/ns0:TDSResponseDescriptionText">
          <ns0:TDSResponseDescriptionText>
            <xsl:value-of select="/imp1:SSACompositeResponse/ns0:ResponseMetadata/ns0:TDSResponseDescriptionText"/>
          </ns0:TDSResponseDescriptionText>
        </xsl:if>
      </ns0:ResponseMetadata>
      <imp1:HavenID>
        <xsl:value-of select="$ConsumeMessage__InputVariable.body/imp1:SSACompositeRequest/ns0:SSACompositeIndividualRequest/ns0:HavenID"/>
      </imp1:HavenID>
      <imp1:RequestNumber>
        <xsl:value-of select="$ConsumeMessage__InputVariable.body/imp1:SSACompositeRequest/ns0:SSACompositeIndividualRequest/ns0:RequestNumber"/>
      </imp1:RequestNumber>
    </imp1:SSACompositeResponse>
  </xsl:template>
</xsl:stylesheet>
