<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions targetNamespace="http://xmlns.oracle.com/enrolapp/getbenchmark/service/wsdl/v1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:WL5G3N2="http://xmlns.oracle.com/enrolapp/getbenchmark/service/wsdl/v1" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
   <plnk:partnerLinkType name="InvokeGetBenchMarkProxy">
      <plnk:role name="GetBechMarkPortType">
         <plnk:portType name="WL5G3N2:GetBechMarkPortType"/>
      </plnk:role>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://xmlns.oracle.com/enrolapp/getbenchmark/service/wsdl/v1" location="InvokeGetBenchMarkProxy.wsdl"/>
</wsdl:definitions>
